### ISSUE TITLE
Using the bundle

### ISSUE THREAD

**Issue by johnmadrak** [vardius/list-bundle#19]
Hello,

I'm using your bundle for a project I'm working on and I found the documentation to be helpful but it didn't explain how to output the generated view.

To get it to work, I'm currently calling `render()` on `ListView` and passing it a `ListDataEvent` with a repository and the request object.

Is this the way that it should be done or did you have another approach in mind?

Thanks for making this bundle!

**Comment by vardius** [comment]
Hi,

The greate example how to create complete list action using this bundle can be found in my crud bundle. Here is the action code: [ListAction.php](https://github.com/Vardius/crud-bundle/blob/master/Actions/Action/ListAction.php), You can lear from this example how does it works. Simply just return params to your view

```
 $params = [
                'list' => $listView->render($listDataEvent),
                'title' => $listView->getTitle(),
            ];
```

And next in your view:

`{{ list|raw }}`

You can check this view here: [list.html.twig](https://github.com/Vardius/crud-bundle/blob/master/Resources/views/Actions/list.html.twig)

I will update the doc, haven't notice that there is no action usage example. Thanks for the info. If you have more further questions just simply let me know. Also i would like to know if you are using specific version or master branch ? If you need me to realeas a new tag from master, so there will not be any errors in the future i can do that.

**Comment by vardius** [comment]
Here is the updated doc: [Usage](https://github.com/Vardius/list-bundle/blob/master/Resources/doc/configuration.md#usage)

**Comment by johnmadrak** [comment]
Hello,

Great, that's how I was doing it. Glad to know that I am doing it the right way. Thanks for adding the usage example to the doc, I think it will be helpful for others in the future.

Right now I'm using 0.5.0. I did notice that there is an issue with 0.5.0 that may be fixed with your current master branch, so if you want to release a new tag I can test that and see if the issue still exists before creating a GitHub issue.

Thanks again.

**Comment by vardius** [comment]
Here you go: [v.0.6.0](https://github.com/Vardius/list-bundle/releases/tag/v0.6.0). I am closing this issue then.
